name: Build
on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        platform:       [ubuntu-latest]
        nim-channel:    [stable]
    name: ${{ matrix.platform }}-${{ matrix.nim-channel }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: ${{ matrix.nim-channel }}

    - name: Build docs
      shell: bash
      run: nim js index.nim
